import express from "express";
import { createServer as createViteServer } from "vite";
import axios from "axios";
import cookieParser from "cookie-parser";
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(cookieParser());
  app.use(express.json());

  // === GitHub OAuth Routes ===

  // 1. Get Auth URL
  app.get('/api/auth/github/url', (req, res) => {
    const clientId = process.env.GITHUB_CLIENT_ID;
    if (!clientId) {
      return res.status(500).json({ error: 'GITHUB_CLIENT_ID not configured' });
    }

    // Determine redirect URI - using window.location.origin on client is best, 
    // but on server we can use the request host header or a predefined one.
    // As per skill guidelines, the client should ideally pass this or we construct it.
    const redirectUri = `${req.protocol}://${req.get('host')}/auth/callback`;
    
    const params = new URLSearchParams({
      client_id: clientId,
      redirect_uri: redirectUri,
      scope: 'repo gist', // Request access to repos and gists
      state: Math.random().toString(36).substring(7)
    });

    res.json({ url: `https://github.com/login/oauth/authorize?${params}` });
  });

  // 2. Callback Handler
  app.get('/auth/callback', async (req, res) => {
    const { code } = req.query;
    const clientId = process.env.GITHUB_CLIENT_ID;
    const clientSecret = process.env.GITHUB_CLIENT_SECRET;

    if (!code || !clientId || !clientSecret) {
      return res.status(400).send('Missing code or configuration');
    }

    try {
      const tokenResponse = await axios.post('https://github.com/login/oauth/access_token', {
        client_id: clientId,
        client_secret: clientSecret,
        code,
      }, {
        headers: { Accept: 'application/json' }
      });

      const { access_token } = tokenResponse.data;

      if (access_token) {
        // Set HTTP-only cookie with iframe compatibility
        res.cookie('github_token', access_token, {
          httpOnly: true,
          secure: true,
          sameSite: 'none',
          maxAge: 30 * 24 * 60 * 60 * 1000 // 30 days
        });

        // Send success message to window.opener as per oauth-integration skill
        res.send(`
          <html>
            <head><title>Authentication Successful</title></head>
            <body style="font-family: sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; background: #000; color: #fff;">
              <script>
                if (window.opener) {
                  window.opener.postMessage({ type: 'OAUTH_AUTH_SUCCESS', provider: 'github' }, '*');
                  window.close();
                } else {
                  window.location.href = '/';
                }
              </script>
              <div style="background: #111; padding: 2rem; border-radius: 12px; border: 1px solid #333; text-align: center;">
                <h1 style="color: #10b981;">Connected!</h1>
                <p>GitHub authentication successful. This window will close automatically.</p>
              </div>
            </body>
          </html>
        `);
      } else {
        res.status(400).send('Failed to obtain access token');
      }
    } catch (error) {
      console.error('GitHub Auth Error:', error);
      res.status(500).send('Authentication failed');
    }
  });

  // 3. Check Status
  app.get('/api/github/status', (req, res) => {
    const token = req.cookies.github_token;
    res.json({ connected: !!token });
  });

  // 4. Logout
  app.post('/api/github/logout', (req, res) => {
    res.clearCookie('github_token', {
      httpOnly: true,
      secure: true,
      sameSite: 'none'
    });
    res.json({ success: true });
  });

  // 5. Deploy to New Repo
  app.post('/api/github/deploy', async (req, res) => {
    const token = req.cookies.github_token;
    if (!token) {
      return res.status(401).json({ error: 'Not authenticated with GitHub' });
    }

    const { repoName, description, files, isPrivate = false } = req.body;

    if (!repoName) {
      return res.status(400).json({ error: 'Repository name is required' });
    }

    try {
      // 1. Create Repository
      const repoRes = await axios.post('https://api.github.com/user/repos', {
        name: repoName,
        description: description || 'Generated by Flash UI',
        private: isPrivate,
        auto_init: true
      }, {
        headers: { 
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github.v3+json'
        }
      });

      const fullRepoName = repoRes.data.full_name;
      const defaultBranch = repoRes.data.default_branch || 'main';

      // 2. Upload Files
      // Note: This is a simplified sequential upload. For many files, a tree-based upload is better.
      const uploadPromises = Object.entries(files).map(async ([path, content]) => {
        try {
          return await axios.put(`https://api.github.com/repos/${fullRepoName}/contents/${path}`, {
            message: `Initial commit: ${path}`,
            content: Buffer.from(content as string).toString('base64'),
            branch: defaultBranch
          }, {
            headers: { 
              Authorization: `Bearer ${token}`,
              Accept: 'application/vnd.github.v3+json'
            }
          });
        } catch (err: any) {
          console.error(`Failed to upload ${path}:`, err.response?.data || err.message);
          throw err;
        }
      });

      await Promise.all(uploadPromises);

      res.json({ 
        success: true, 
        url: repoRes.data.html_url,
        fullName: fullRepoName
      });
    } catch (error: any) {
      console.error('GitHub Deployment Error:', error.response?.data || error.message);
      res.status(500).json({ 
        error: 'Failed to deploy to GitHub', 
        details: error.response?.data?.message || error.message 
      });
    }
  });

  // === Custom APIs ===

  // Example API: Health Check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", timestamp: new Date().toISOString() });
  });

  // Example API: User Settings (JSON storage simulation)
  let mockDatabase = { settings: { theme: 'dark', notifications: true } };
  app.get("/api/settings", (req, res) => {
    res.json(mockDatabase.settings);
  });

  app.post("/api/settings", (req, res) => {
    mockDatabase.settings = { ...mockDatabase.settings, ...req.body };
    res.json({ success: true, settings: mockDatabase.settings });
  });

  // === Webhook Receiver ===

  /**
   * Webhook handler for external services (e.g., Stripe, Shopify, GitHub)
   * In a real app, you would verify the signature here.
   */
  app.post("/api/webhooks/incoming", (req, res) => {
    const payload = req.body;
    const signature = req.headers['x-webhook-signature']; // Example header

    console.log("Received Webhook Payload:", payload);
    
    // Process the webhook asynchronously
    if (payload.event === 'order.created') {
      console.log(`Processing new order: ${payload.orderId}`);
    }

    // Always respond quickly with 200 or 202 to the sender
    res.status(202).json({ received: true });
  });

  // === Vite Middleware ===
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Serve static files in production
    app.use(express.static('dist'));
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
